mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/odi-core.jar -DgroupId=org.oracle.odisdk -DartifactId=odi-core -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/spring-core.jar -DgroupId=org.oracle.odisdk -DartifactId=spring-core -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/dms.jar -DgroupId=org.oracle.odisdk -DartifactId=dms -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/ojdl.jar -DgroupId=org.oracle.odisdk -DartifactId=ojdl -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/SchemaVersion.jar -DgroupId=org.oracle.odisdk -DartifactId=SchemaVersion -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/commons-lang-2.2.jar -DgroupId=org.oracle.odisdk -DartifactId=commons-lang-2.2 -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/spring-jdbc.jar -DgroupId=org.oracle.odisdk -DartifactId=spring-jdbc -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/spring-dao.jar -DgroupId=org.oracle.odisdk -DartifactId=spring-dao -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/spring-beans.jar -DgroupId=org.oracle.odisdk -DartifactId=spring-beans -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/commons-logging-1.1.1.jar -DgroupId=org.oracle.odisdk -DartifactId=commons-logging-1.1.1 -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/bsf.jar -DgroupId=org.oracle.odisdk -DartifactId=bsf -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/bsh-2.0b2.jar -DgroupId=org.oracle.odisdk -DartifactId=bsh-2.0b2 -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/javolution.jar -DgroupId=org.oracle.odisdk -DartifactId=javolution -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/eclipselink.jar -DgroupId=org.oracle.odisdk -DartifactId=eclipselink -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/persistence.jar -DgroupId=org.oracle.odisdk -DartifactId=persistence -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/oracle.ucp_11.1.0.jar -DgroupId=org.oracle.odisdk -DartifactId=oracle.ucp_11.1.0 -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/oracledi.sdk/lib/commons-collections-3.2.jar -DgroupId=org.oracle.odisdk -DartifactId=commons-collections-3.2 -Dversion=11.1.1 -Dpackaging=jar

mvn install:install-file -Dfile=$ODI_HOME/modules/oracle.jdbc_11.1.1/ojdbc6dms.jar -DgroupId=org.oracle.odisdk -DartifactId=ojdbc6dms -Dversion=11.1.1 -Dpackaging=jar
mvn install:install-file -Dfile=$ODI_HOME/modules/oracle.jps_11.1.1/jps-api.jar -DgroupId=org.oracle.odisdk -DartifactId=jps-api -Dversion=11.1.1 -Dpackaging=jar
